#!/bin/sh

urlregex="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:;a-zA-Z0-9./+@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

urls="$(sed 's/.*│//g' | tr -d '\n' | # First remove linebreaks and mutt sidebars:
	grep -aEo "$urlregex" | # grep only urls as defined above.
	uniq | # Ignore neighboring duplicates.
	sed "s/\(\.\|,\|;\|\!\\|\?\)$//;
	s/^www./http:\/\/www\./")" # xdg-open will not detect url without http

[ -z "$urls" ] && exit 1

while getopts "hoc" o; do case "${o}" in
	o) chosen="$(echo "$urls" | dmenu -i -p 'Follow url:' -l 10)" setsid xdg-open "$chosen" >/dev/null 2>&1 & ;;
	c) echo "$urls" | dmenu -i -p 'Copy url:' -l 10 | tr -d '\n' | xclip -selection clipboard ;;
esac done
